Repository woopstar/hsem, pull requests merged in 2024-10, with the labels that each got.

#7 fix: remove binary_sensor and fix working_mode_sensor
  custom_components/hsem/binary_sensor.py
  custom_components/hsem/custom_sensors/export_sensor.py
  custom_components/hsem/custom_sensors/house_consumption_power_sensor.py
  custom_components/hsem/custom_sensors/import_sensor.py
  custom_components/hsem/custom_sensors/working_mode_sensor.py
  custom_components/hsem/sensor.py
Labels: breaking-change, minor

#8 fix: add ev sensors to config flow
  custom_components/hsem/config_flow.py
  custom_components/hsem/const.py
  custom_components/hsem/custom_sensors/working_mode_sensor.py
  custom_components/hsem/sensor.py
  custom_components/hsem/translations/en.json
Labels: minor

#9 Fix power sensors to include ev data
  custom_components/hsem/custom_sensors/house_consumption_energy_average_sensor.py
  custom_components/hsem/custom_sensors/house_consumption_energy_sensor.py
  custom_components/hsem/custom_sensors/house_consumption_power_sensor.py
  custom_components/hsem/custom_sensors/working_mode_sensor.py
  custom_components/hsem/sensor.py
Labels: patch

#10 fix: house_consumption_energy_sensor
  custom_components/hsem/custom_sensors/house_consumption_energy_sensor.py
  custom_components/hsem/custom_sensors/house_consumption_power_sensor.py
Labels: patch

#11 fix: initial fixes for energy average sensors
  custom_components/hsem/custom_sensors/house_consumption_energy_average_sensor.py
  custom_components/hsem/custom_sensors/house_consumption_energy_sensor.py
  custom_components/hsem/custom_sensors/house_consumption_power_sensor.py
Labels: patch

#15 add: created initial doc for each file and corrected a few danish comments
  custom_components/hsem/__init__.py
  custom_components/hsem/config_flow.py
  custom_components/hsem/const.py
  custom_components/hsem/custom_sensors/house_consumption_energy_average_sensor.py
  custom_components/hsem/custom_sensors/house_consumption_energy_sensor.py
  custom_components/hsem/custom_sensors/house_consumption_power_sensor.py
  custom_components/hsem/custom_sensors/working_mode_sensor.py
  custom_components/hsem/entity.py
  custom_components/hsem/sensor.py
  custom_components/hsem/utils/ha.py
  custom_components/hsem/utils/huawei.py
  custom_components/hsem/utils/misc.py
  custom_components/hsem/utils/workingmodes.py
Labels: enhancement, chore

#16 fix: remove blocking call
  custom_components/hsem/utils/huawei.py
Labels: patch
